### ISSUE TITLE
wiki is inaccessible

### ISSUE THREAD

**Issue by meltir** [fluxbox-wiki/fluxbox-wiki.github.io#84]
The fluxbox-wiki.org domain is returning errors, and the default fluxbox-wiki.github.io domain redirects to it.  
The page returns a tinyurl error:  

```
The TinyURL (UpdatersChrome) you visited was used by its creator in violation of our terms of use. TinyURL has a strict no abuse policy and we apologize for the intrusion this user has caused you. Such violations of our terms of use include:

Spam - Unsolicited Bulk Email
Fraud or Money Making scams
Malware
or any other use that is illegal.
If you received spam, please note that TinyURL did not send this spam and we do not operate any email lists. We can not remove you from spammer's database as we have no association with spammers, but instead we recommend you use spam filtering software.
```

**Comment by mgumz** [comment]
@meltir i merged #85 … this should fix this issue here

**Comment by meltir** [comment]
Happy with this, now http://fluxbox-wiki.github.io/ is up.
Known issues:
- [**www**.fluxbox-wiki.github.io](http://www.fluxbox-wiki.github.io/) 404's
- absolute links to css/js break stuff:
  - https blocks mixed content - css/js
  - search is looking for links in site:www.fluxbox-wiki.github.io (which 404's)
  - TOC is not loading (links go to www.)

(Ill create another ticket)  

Workaround:  
to navigate the pages, go to http://fluxbox-wiki.github.io/ and select a language to get a listing of available pages.

**Comment by Nable80** [comment]
@mgumz
Some links to ``fluxbox-wiki.org`` remained at ``fluxbox.org``, at least in the ``GIT DEVELOPMENT VERSION`` section of http://fluxbox.org/download/, ``WIKI`` at http://fluxbox.org/help/ plus some links on http://fluxbox.org/features/ ...

Could you fix it, please?

**Comment by mgumz** [comment]
@Nable80 is there a reason you slap a request to an arbitrary issue? 

your mentioned issues: fixed.

**Comment by Nable80** [comment]
Thank you very much for fixing it so quick!

Regarding my choice, well, at that moment it didn't look arbitrary for me, sorry…

At first I tried to find when the domain change happened (looking through snapshots at archive.org), then found commit 62672f703c25967711a19c39253352c3fba7a591 which changed URLs, it was a part of an already merged PR that is mentioned here, so I thought it makes some sense to report it here (title of the issue seems relevant enough) without creating duplicate issues. There may be a better place but I guess I didn't spend enough time looking for it.

Upd: OK, I finally found the right place that mentions exactly these problems: https://github.com/fluxbox/fluxbox.org/issues/4
I have completely overlooked that whole repo somehow, my bad.
